### PR TITLE
Add extra variables for configuring XCache

### PR DESCRIPTION
**Pull request by matyasselmeci**
We need these to be able to override various things for testing.

### CODE REVIEW

**Comment by brianhlin** [comment]
Is this just for testing or do we expect users to actually want to change the HTTP/S ports?

**Comment by matyasselmeci** [comment]
Just for testing (although who knows what people making Kubernetes configs are gonna do...)

**Comment by brianhlin** [comment]
I would think that anyone using containers would prefer having a standard port inside the container itself that they can publish on a different port outside of the container with docker/k8s.

Let's just tag and build 1.0.2 without this. In our tests we're free to drop whatever config we want to override what's in the packaging. We've got 11 tickets that need testing that are waiting on a build.

**Comment by matyasselmeci** [comment]
I want to at least get the Authfile variable commit (and the comment fix) in there... we have those variables for overriding the origin Authfiles; we should have them for the cache Authfiles too.

**Comment by brianhlin** [comment]
I'm ok with that.

**Pull request merged**
