### PR TITLE
Reducing the amount of logging by default

### PR DESCRIPTION
**Pull request by efajardo**
@oschar and @abh3 can you comment on these?

### CODE REVIEW

**Comment by abh3** [comment]
The following directives should simply be removed. There is no "info" level to tracing. Tracing for these components is strictly meant for developer debugging and has no place in a production (i.e. operational) setting. The "pfc.trace info" is OK but even that may produce more than you would like.

Remove:
ofs.trace info
xrd.trace info -sched
cms.trace info
http.trace info

**Comment by efajardo** [comment]
thanks @abh3

**Comment by brianhlin** [comment]
@efajardo don't forget to create that JIRA ticket and apply any relevant changes to `osg-xrootd`!

**Comment by brianhlin** [comment]
@efajardo ping

**Pull request merged**
