### PR TITLE
drop configs moving to osg-xrootd package (SOFTWARE-3520)

### PR DESCRIPTION
**Pull request by edquist**
These config files are moving to a new `osg-xrootd` package.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
We will need to wait until osg-xrootd is ready, plus update the spec file for this, before it is merged.
Actually, @edquist, you can update the spec file now -- make the appropriate changes in rpm/xcache.spec to remove these files and add osg-xrootd as a dependency.

**Comment by brianhlin** [comment]
I believe this can be merged now since we've released osg-xrootd. @edquist please verify and remove the label/merge as appropriate

**Comment by edquist** [comment]
Looks like rpm/xcache.spec file still needs to be updated.

@matyasselmeci, just to confirm - we want the main `xcache` rpm to require `osg-xrootd` ?

**Comment by matyasselmeci** [comment]
I think so. It's been a while.

**Comment by brianhlin** [comment]
> we want the main xcache rpm to require osg-xrootd ?

Correct!

**Comment by brianhlin** [comment]
> Looks like rpm/xcache.spec file still needs to be updated.

@edquist please add commits for the necessary updates

**Comment by matyasselmeci** [comment]
I don't think we're planning to make any more xcache V2 releases so I'm closing this.

**Pull request closed without merging**
